sudo: required
services:
  - docker
before_install:
  - docker build -t kunwarluthera/python-flask-demo-api .
script:
  - docker run -d kunwarluthera/python-flask-demo-api python app.py -- --coverage
after_success:
  - docker build -t kunwarluthera/python-flask-demo-api .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kunwarluthera/python-flask-demo-api
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "DockerFlask-env"
  bucket_name: "elasticbeanstalk-us-east-1-738585724471"
  bucket_path: "docker-python"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"