sudo: required
services:
  - docker
before_install:
  - docker build -t kunwarluthera/python-flask-demo-api .
script:
  - docker run kunwarluthera/python-flask-demo-api -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker-Python"
  env: "DockerPython-env"
  bucket_name: "elasticbeanstalk-us-east-1-738585724471"
  bucket_path: "docker-python"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"