version: '3'
services:
  python-app:
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5000"