version: '3'
services:
  python-dev-app:
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "5001:5000"